const { MongoClient } = require('mongodb');
const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');

const MONGO_URL = process.env.MONGO_URL || 'mongodb://localhost:27017';
const DB_NAME = process.env.DB_NAME || 'your_database_name';

async function seed() {
  const client = new MongoClient(MONGO_URL);
  await client.connect();
  const db = client.db(DB_NAME);
  console.log('Connected to MongoDB');

  const defaultPwHash = await bcrypt.hash('Welcome@1cf', 10);

  // ===== USERS =====
  const users = [
    // --- 30 DOCTORS ---
    { name:'Dr Aarav Mehta', email:'aarav.mehta@seed.1cofounder', role:'Doctor', city:'Delhi', country:'India', bio:'Cardiologist exploring AI tools for ECG interpretation in rural clinics. 8 years of clinical experience in tertiary care hospitals.', skills:['Cardiology','Clinical Research','ECG Interpretation'], interests:['AI Healthcare','Remote Monitoring','Diagnostics'], stage:'Validation', commit:'Part Time', lookingFor:['AI Engineer','Data Scientist'] },
    { name:'Dr Priya Sharma', email:'priya.sharma@seed.1cofounder', role:'Doctor', city:'Mumbai', country:'India', bio:'Radiologist building automated CT scan screening workflows for district hospitals. Published 12 papers on AI-assisted diagnostics.', skills:['Radiology','Medical Imaging','Clinical Trials'], interests:['AI Healthcare','Diagnostics','Digital Health'], stage:'MVP', commit:'Full Time', lookingFor:['Software Engineer','AI Engineer'] },
    { name:'Dr Rohan Gupta', email:'rohan.gupta@seed.1cofounder', role:'Doctor', city:'Bangalore', country:'India', bio:'ICU physician investigating predictive monitoring systems for early sepsis detection in resource-limited settings.', skills:['ICU Medicine','Critical Care','Sepsis Management'], interests:['AI Healthcare','Remote Monitoring','Hospital Automation'], stage:'Idea', commit:'Part Time', lookingFor:['AI Engineer','Hardware Engineer'] },
    { name:'Dr Sneha Reddy', email:'sneha.reddy@seed.1cofounder', role:'Doctor', city:'Hyderabad', country:'India', bio:'Neonatologist designing low-cost neonatal monitoring devices for government maternity hospitals in Telangana.', skills:['Pediatrics','Neonatology','Public Health'], interests:['Medical Devices','Womens Health','Remote Monitoring'], stage:'Validation', commit:'Part Time', lookingFor:['Biomedical Engineer','Product Manager'] },
    { name:'Dr Vikram Singh', email:'vikram.singh@seed.1cofounder', role:'Doctor', city:'Chennai', country:'India', bio:'Ophthalmologist developing smartphone-based retinal screening for diabetic patients in rural Tamil Nadu.', skills:['Ophthalmology','Retinal Imaging','Diabetes Care'], interests:['AI Healthcare','Diagnostics','Digital Health'], stage:'MVP', commit:'Full Time', lookingFor:['Mobile Developer','AI Engineer'] },
    { name:'Dr Ananya Iyer', email:'ananya.iyer@seed.1cofounder', role:'Doctor', city:'Pune', country:'India', bio:'Psychiatrist working on digital CBT platforms for anxiety and depression management in young professionals.', skills:['Psychiatry','Cognitive Behavioral Therapy','Mental Health'], interests:['Mental Health','Digital Therapeutics','Health Apps'], stage:'Idea', commit:'Part Time', lookingFor:['Software Engineer','UX Researcher'] },
    { name:'Dr Karthik Nair', email:'karthik.nair@seed.1cofounder', role:'Doctor', city:'Kolkata', country:'India', bio:'Emergency medicine physician prototyping triage algorithms for overcrowded urban emergency departments.', skills:['Emergency Medicine','Triage Systems','Clinical Decision Support'], interests:['AI Healthcare','Hospital Automation','Clinical Decision Support'], stage:'Validation', commit:'Part Time', lookingFor:['AI Engineer','Software Engineer'] },
    { name:'Dr Meera Joshi', email:'meera.joshi@seed.1cofounder', role:'Doctor', city:'Ahmedabad', country:'India', bio:'Dermatologist creating AI-powered skin lesion classification tools trained on Indian skin tones.', skills:['Dermatology','Clinical Research','Pattern Recognition'], interests:['AI Healthcare','Diagnostics','Precision Medicine'], stage:'MVP', commit:'Full Time', lookingFor:['Machine Learning Engineer','Data Scientist'] },
    { name:'Dr Arjun Patel', email:'arjun.patel@seed.1cofounder', role:'Doctor', city:'Jaipur', country:'India', bio:'Orthopedic surgeon evaluating AR-guided surgical navigation for complex fracture fixation procedures.', skills:['Orthopedics','Surgery','Biomechanics'], interests:['Surgical Robotics','Medical Devices','Augmented Reality Surgery'], stage:'Idea', commit:'Part Time', lookingFor:['Hardware Engineer','Software Engineer'] },
    { name:'Dr Divya Krishnan', email:'divya.krishnan@seed.1cofounder', role:'Doctor', city:'Chandigarh', country:'India', bio:'Pulmonologist building spirometry-based COPD screening tools for primary health centers across Punjab.', skills:['Pulmonology','Respiratory Medicine','Public Health'], interests:['Diagnostics','Remote Monitoring','Digital Health'], stage:'Validation', commit:'Part Time', lookingFor:['Biomedical Engineer','Data Scientist'] },
    { name:'Dr Siddharth Rao', email:'siddharth.rao@seed.1cofounder', role:'Doctor', city:'Bangalore', country:'India', bio:'Gastroenterologist developing endoscopy image analysis tools for early detection of colorectal abnormalities.', skills:['Gastroenterology','Endoscopy','Clinical Research'], interests:['AI Healthcare','Diagnostics','Oncology Innovation'], stage:'MVP', commit:'Part Time', lookingFor:['AI Engineer','Product Manager'] },
    { name:'Dr Neha Kapoor', email:'neha.kapoor@seed.1cofounder', role:'Doctor', city:'Delhi', country:'India', bio:'OB-GYN creating a maternal health tracking app for high-risk pregnancies in semi-urban India.', skills:['Obstetrics & Gynecology','Maternal Health','Antenatal Care'], interests:['Womens Health','Remote Monitoring','Health Apps'], stage:'Validation', commit:'Full Time', lookingFor:['Mobile Developer','UX Researcher'] },
    { name:'Dr Rahul Deshmukh', email:'rahul.deshmukh@seed.1cofounder', role:'Doctor', city:'Pune', country:'India', bio:'Nephrologist investigating wearable biomarker sensors for early chronic kidney disease detection.', skills:['Nephrology','Biomarkers','Clinical Trials'], interests:['Wearable Health Tech','Diagnostics','Chronic Disease Management'], stage:'Idea', commit:'Part Time', lookingFor:['Biomedical Engineer','Hardware Engineer'] },
    { name:'Dr Ishita Banerjee', email:'ishita.banerjee@seed.1cofounder', role:'Doctor', city:'Kolkata', country:'India', bio:'Pediatric intensivist designing real-time vital sign dashboards for pediatric ICUs with limited nursing staff.', skills:['Pediatrics','ICU Medicine','Patient Safety'], interests:['Hospital Automation','Remote Monitoring','AI Healthcare'], stage:'Validation', commit:'Part Time', lookingFor:['Software Engineer','Data Scientist'] },
    { name:'Dr Aditya Kulkarni', email:'aditya.kulkarni@seed.1cofounder', role:'Doctor', city:'Mumbai', country:'India', bio:'Endocrinologist building an insulin dose optimization engine using continuous glucose monitor data.', skills:['Endocrinology','Diabetes Care','Data Analysis'], interests:['AI Healthcare','Precision Medicine','Digital Therapeutics'], stage:'MVP', commit:'Full Time', lookingFor:['AI Engineer','Mobile Developer'] },
    { name:'Dr Pooja Saxena', email:'pooja.saxena@seed.1cofounder', role:'Doctor', city:'Hyderabad', country:'India', bio:'Hematologist researching point-of-care blood count analyzers for rural diagnostic labs.', skills:['Hematology','Diagnostics','Point-of-Care Testing'], interests:['Medical Devices','Diagnostics','Rural Healthcare'], stage:'Idea', commit:'Part Time', lookingFor:['Biomedical Engineer','Hardware Engineer'] },
    { name:'Dr Manish Tiwari', email:'manish.tiwari@seed.1cofounder', role:'Doctor', city:'Chennai', country:'India', bio:'Anesthesiologist developing automated pre-operative risk scoring tools integrated with hospital EMRs.', skills:['Anesthesiology','Risk Assessment','Health Informatics'], interests:['Clinical Decision Support','Hospital Automation','AI Healthcare'], stage:'Validation', commit:'Part Time', lookingFor:['Software Engineer','Data Scientist'] },
    { name:'Dr Ritu Agarwal', email:'ritu.agarwal@seed.1cofounder', role:'Doctor', city:'Jaipur', country:'India', bio:'Community medicine specialist designing WhatsApp-based TB treatment adherence systems for DOTS programs.', skills:['Public Health','Community Medicine','TB Management'], interests:['Digital Health','Rural Healthcare','Health Communication'], stage:'Validation', commit:'Part Time', lookingFor:['Software Engineer','Product Manager'] },
    { name:'Dr Sameer Choudhury', email:'sameer.choudhury@seed.1cofounder', role:'Doctor', city:'Chandigarh', country:'India', bio:'Cardiologist evaluating AI auscultation devices for rheumatic heart disease screening in school children.', skills:['Cardiology','Pediatric Cardiology','Screening Programs'], interests:['AI Healthcare','Medical Devices','Diagnostics'], stage:'Idea', commit:'Part Time', lookingFor:['AI Engineer','Biomedical Engineer'] },
    { name:'Dr Kavita Menon', email:'kavita.menon@seed.1cofounder', role:'Doctor', city:'Bangalore', country:'India', bio:'Geriatrician building a fall-risk prediction dashboard for elderly care facilities using accelerometer data.', skills:['Geriatrics','Rehabilitation','Fall Prevention'], interests:['Wearable Health Tech','Elder Care','AI Healthcare'], stage:'Validation', commit:'Part Time', lookingFor:['Data Scientist','Hardware Engineer'] },
    { name:'Dr Nikhil Verma', email:'nikhil.verma@seed.1cofounder', role:'Doctor', city:'Delhi', country:'India', bio:'Interventional radiologist creating 3D-printed vascular models from CT angiography for pre-procedural planning.', skills:['Radiology','3D Printing','Vascular Medicine'], interests:['Medical Devices','Surgical Innovation','3D Printing'], stage:'MVP', commit:'Part Time', lookingFor:['Biomedical Engineer','Software Engineer'] },
    { name:'Dr Shreya Das', email:'shreya.das@seed.1cofounder', role:'Doctor', city:'Mumbai', country:'India', bio:'Infectious disease specialist developing antimicrobial stewardship dashboards for multi-drug resistant infections.', skills:['Infectious Disease','Antimicrobial Stewardship','Epidemiology'], interests:['Hospital Automation','Health Data','AI Healthcare'], stage:'Idea', commit:'Part Time', lookingFor:['Software Engineer','Data Scientist'] },
    { name:'Dr Amit Bhatt', email:'amit.bhatt@seed.1cofounder', role:'Doctor', city:'Ahmedabad', country:'India', bio:'Sports medicine physician creating biomechanical analysis tools for ACL injury prevention in cricket players.', skills:['Sports Medicine','Biomechanics','Injury Prevention'], interests:['Wearable Health Tech','Sports Medicine Tech','AI Healthcare'], stage:'Idea', commit:'Part Time', lookingFor:['Biomedical Engineer','Data Scientist'] },
    { name:'Dr Lakshmi Subramaniam', email:'lakshmi.s@seed.1cofounder', role:'Doctor', city:'Chennai', country:'India', bio:'Pathologist developing whole-slide imaging AI for automated cervical cytology screening in cancer programs.', skills:['Pathology','Cytology','Medical Imaging'], interests:['AI Healthcare','Diagnostics','Oncology Innovation'], stage:'MVP', commit:'Full Time', lookingFor:['AI Engineer','Software Engineer'] },
    { name:'Dr Gaurav Mishra', email:'gaurav.mishra@seed.1cofounder', role:'Doctor', city:'Pune', country:'India', bio:'Neurologist researching EEG-based biomarkers for early Alzheimer detection using machine learning classifiers.', skills:['Neurology','EEG Analysis','Neuroscience'], interests:['AI Healthcare','Neurotechnology','Diagnostics'], stage:'Validation', commit:'Part Time', lookingFor:['AI Engineer','Data Scientist'] },
    { name:'Dr Swati Pandey', email:'swati.pandey@seed.1cofounder', role:'Doctor', city:'Hyderabad', country:'India', bio:'Family medicine physician piloting voice-based health record systems for illiterate patients in Telangana villages.', skills:['Family Medicine','Primary Care','Health Communication'], interests:['Digital Health','Rural Healthcare','Voice Technology'], stage:'Idea', commit:'Part Time', lookingFor:['Software Engineer','UX Researcher'] },
    { name:'Dr Rajesh Kumar', email:'rajesh.kumar@seed.1cofounder', role:'Doctor', city:'Kolkata', country:'India', bio:'Oncologist building cancer registry analytics platform for treatment outcome tracking across eastern India.', skills:['Oncology','Clinical Research','Data Analysis'], interests:['Health Data','Oncology Innovation','AI Healthcare'], stage:'Validation', commit:'Part Time', lookingFor:['Data Scientist','Software Engineer'] },
    { name:'Dr Tanvi Shetty', email:'tanvi.shetty@seed.1cofounder', role:'Doctor', city:'Bangalore', country:'India', bio:'ENT surgeon developing AI-powered audiometry screening for newborn hearing loss detection programs.', skills:['ENT Surgery','Audiology','Neonatal Screening'], interests:['AI Healthcare','Medical Devices','Pediatric Health'], stage:'Idea', commit:'Part Time', lookingFor:['AI Engineer','Biomedical Engineer'] },
    { name:'Dr Harsh Vardhan', email:'harsh.vardhan@seed.1cofounder', role:'Doctor', city:'Jaipur', country:'India', bio:'Urologist investigating telemedicine follow-up protocols for post-operative kidney stone patients in Rajasthan.', skills:['Urology','Telemedicine','Clinical Protocols'], interests:['Telemedicine','Digital Health','Remote Monitoring'], stage:'Validation', commit:'Part Time', lookingFor:['Software Engineer','Product Manager'] },
    { name:'Dr Nisha Mathur', email:'nisha.mathur@seed.1cofounder', role:'Doctor', city:'Delhi', country:'India', bio:'Allergist creating environmental pollen tracking and asthma exacerbation prediction system for North India.', skills:['Allergy & Immunology','Pulmonology','Environmental Health'], interests:['AI Healthcare','Remote Monitoring','Preventive Medicine'], stage:'Idea', commit:'Part Time', lookingFor:['Data Scientist','Mobile Developer'] },

    // --- 25 ENGINEERS ---
    { name:'Ankit Sharma', email:'ankit.sharma@seed.1cofounder', role:'Engineer', city:'Bangalore', country:'India', bio:'ML engineer specializing in medical image segmentation. Built retinal vessel detection models at a health-tech startup.', skills:['Machine Learning','Deep Learning','Computer Vision','Python'], interests:['AI Healthcare','Diagnostics','Medical Image Analysis'], stage:'Exploring', commit:'Full Time', lookingFor:['Clinician','Product Manager'] },
    { name:'Riya Patel', email:'riya.patel@seed.1cofounder', role:'Engineer', city:'Hyderabad', country:'India', bio:'Full-stack developer with 5 years building HIPAA-compliant health platforms. Experienced with FHIR and HL7 standards.', skills:['Full Stack Development','React','Backend Development','Health Informatics'], interests:['Digital Health','EHR Innovation','Health Data'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Business Operator'] },
    { name:'Deepak Jain', email:'deepak.jain@seed.1cofounder', role:'Engineer', city:'Delhi', country:'India', bio:'NLP engineer working on clinical note extraction and medical entity recognition from unstructured Hindi health records.', skills:['Natural Language Processing','Machine Learning','Python','Data Engineering'], interests:['AI Healthcare','Health Data','Clinical Decision Support'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Data Scientist'] },
    { name:'Megha Rao', email:'megha.rao@seed.1cofounder', role:'Engineer', city:'Mumbai', country:'India', bio:'Mobile developer building offline-first Android health apps for community health workers in Maharashtra.', skills:['Mobile Development (Android)','Flutter','Offline Systems','UX Design'], interests:['Digital Health','Rural Healthcare','Health Apps'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Public Health Expert'] },
    { name:'Suresh Venkatesh', email:'suresh.v@seed.1cofounder', role:'Engineer', city:'Chennai', country:'India', bio:'Cloud architect designing scalable teleradiology platforms. Previously at a PACS vendor handling 10M+ scans.', skills:['Cloud Architecture','DevOps','System Design','Medical Imaging'], interests:['Digital Health','AI Healthcare','Telemedicine'], stage:'Exploring', commit:'Part Time', lookingFor:['Clinician','Product Manager'] },
    { name:'Prachi Desai', email:'prachi.desai@seed.1cofounder', role:'Engineer', city:'Pune', country:'India', bio:'AI engineer focused on federated learning for multi-hospital clinical prediction models without sharing patient data.', skills:['Machine Learning','Federated Learning','AI Ethics','Python'], interests:['AI Healthcare','Health Data Privacy','Predictive Analytics'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Regulatory Specialist'] },
    { name:'Rahul Nair', email:'rahul.nair@seed.1cofounder', role:'Engineer', city:'Bangalore', country:'India', bio:'Backend engineer building real-time patient monitoring data pipelines processing 50K+ vital sign events per second.', skills:['Backend Development','Data Engineering','Microservices','Kafka'], interests:['Hospital Automation','Remote Monitoring','Health Data'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Hardware Engineer'] },
    { name:'Kritika Gupta', email:'kritika.gupta@seed.1cofounder', role:'Engineer', city:'Delhi', country:'India', bio:'Computer vision engineer developing automated diabetic retinopathy grading systems for ophthalmology clinics.', skills:['Computer Vision','Deep Learning','Medical Image Analysis','TensorFlow'], interests:['AI Healthcare','Diagnostics','Ophthalmology Tech'], stage:'MVP', commit:'Full Time', lookingFor:['Doctor','Data Scientist'] },
    { name:'Vivek Menon', email:'vivek.menon@seed.1cofounder', role:'Engineer', city:'Kolkata', country:'India', bio:'Cybersecurity engineer specializing in healthcare data protection and EHR penetration testing for hospital networks.', skills:['Cybersecurity','Backend Development','HIPAA Compliance','API Development'], interests:['Health Data Privacy','Digital Health','Hospital Automation'], stage:'Exploring', commit:'Part Time', lookingFor:['Business Operator','Clinician'] },
    { name:'Aishwarya Reddy', email:'aishwarya.reddy@seed.1cofounder', role:'Engineer', city:'Hyderabad', country:'India', bio:'MLOps engineer streamlining deployment of clinical ML models with monitoring for data drift in hospital settings.', skills:['MLOps','Machine Learning','DevOps','Docker'], interests:['AI Healthcare','Digital Health','Clinical Decision Support'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Product Manager'] },
    { name:'Nitin Aggarwal', email:'nitin.aggarwal@seed.1cofounder', role:'Engineer', city:'Chandigarh', country:'India', bio:'React developer building patient portal interfaces. Focused on accessibility for elderly and visually impaired users.', skills:['Frontend Development','React','Accessibility Design','UI Design'], interests:['Digital Health','Health Apps','Elder Care'], stage:'Exploring', commit:'Part Time', lookingFor:['Clinician','UX Researcher'] },
    { name:'Sakshi Tomar', email:'sakshi.tomar@seed.1cofounder', role:'Engineer', city:'Jaipur', country:'India', bio:'Embedded systems engineer developing low-power BLE medical device firmware for wearable vital monitors.', skills:['Embedded Systems','Firmware','Bluetooth Low Energy','C/C++'], interests:['Wearable Health Tech','Medical Devices','Remote Monitoring'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Biomedical Engineer'] },
    { name:'Aman Tripathi', email:'aman.tripathi@seed.1cofounder', role:'Engineer', city:'Mumbai', country:'India', bio:'Data pipeline engineer building ETL systems that normalize clinical data from 200+ hospital EMR formats.', skills:['Data Engineering','ETL Pipelines','SQL','Python'], interests:['Health Data','EHR Innovation','Clinical Data Management'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Product Manager'] },
    { name:'Nidhi Chauhan', email:'nidhi.chauhan@seed.1cofounder', role:'Engineer', city:'Ahmedabad', country:'India', bio:'iOS developer creating intuitive medication adherence apps with smart pill reminder algorithms.', skills:['Mobile Development (iOS)','Swift','UX Design','Health Apps'], interests:['Digital Health','Health Apps','Chronic Disease Management'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Business Operator'] },
    { name:'Karan Bhatia', email:'karan.bhatia@seed.1cofounder', role:'Engineer', city:'Pune', country:'India', bio:'Speech recognition engineer building Hindi and Marathi voice interfaces for hands-free clinical documentation.', skills:['Speech Recognition','Natural Language Processing','Python','Deep Learning'], interests:['AI Healthcare','Digital Health','Voice Technology'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Product Manager'] },
    { name:'Shreyas Kulkarni', email:'shreyas.k@seed.1cofounder', role:'Engineer', city:'Bangalore', country:'India', bio:'Robotics engineer developing autonomous medication dispensing systems for hospital pharmacy automation.', skills:['Robotics','Embedded Systems','Computer Vision','ROS'], interests:['Hospital Automation','Medical Devices','Surgical Robotics'], stage:'Idea', commit:'Part Time', lookingFor:['Clinician','Business Operator'] },
    { name:'Pallavi Singh', email:'pallavi.singh@seed.1cofounder', role:'Engineer', city:'Delhi', country:'India', bio:'Blockchain developer implementing tamper-proof clinical trial data recording and consent management systems.', skills:['Blockchain','Smart Contracts','Backend Development','Cryptography'], interests:['Clinical Trial Innovation','Health Data Privacy','Digital Health'], stage:'Idea', commit:'Part Time', lookingFor:['Clinical Researcher','Regulatory Specialist'] },
    { name:'Varun Deshpande', email:'varun.deshpande@seed.1cofounder', role:'Engineer', city:'Chennai', country:'India', bio:'Reinforcement learning engineer optimizing hospital bed allocation and OR scheduling algorithms.', skills:['Reinforcement Learning','Machine Learning','Operations Research','Python'], interests:['Hospital Automation','AI Healthcare','Healthcare Operations'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Healthcare Consultant'] },
    { name:'Aditi Saxena', email:'aditi.saxena@seed.1cofounder', role:'Engineer', city:'Hyderabad', country:'India', bio:'QA automation engineer building testing frameworks for medical device software under IEC 62304 compliance.', skills:['Quality Assurance','Test Automation','Medical Device Software','IEC 62304'], interests:['Medical Devices','Digital Health','Regulatory Affairs'], stage:'Exploring', commit:'Part Time', lookingFor:['Regulatory Specialist','Product Manager'] },
    { name:'Rohit Saxena', email:'rohit.saxena@seed.1cofounder', role:'Engineer', city:'Mumbai', country:'India', bio:'Signal processing engineer developing acoustic analysis algorithms for digital stethoscope heart murmur detection.', skills:['Signal Processing','Machine Learning','Audio Processing','MATLAB'], interests:['Medical Devices','AI Healthcare','Diagnostics'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Biomedical Engineer'] },
    { name:'Tanya Kapoor', email:'tanya.kapoor@seed.1cofounder', role:'Engineer', city:'Kolkata', country:'India', bio:'DevOps engineer managing HIPAA-compliant Kubernetes clusters for healthtech SaaS platforms serving 100+ clinics.', skills:['DevOps','Kubernetes','Cloud Architecture','Site Reliability Engineering'], interests:['Digital Health','Hospital Automation','Health Data'], stage:'Exploring', commit:'Part Time', lookingFor:['Clinician','Business Operator'] },
    { name:'Jay Prakash', email:'jay.prakash@seed.1cofounder', role:'Engineer', city:'Chandigarh', country:'India', bio:'Full-stack developer building telemedicine video consultation platforms with real-time translation for regional languages.', skills:['Full Stack Development','WebRTC','React','Node.js'], interests:['Telemedicine','Digital Health','Rural Healthcare'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Product Manager'] },
    { name:'Sonal Mehta', email:'sonal.mehta@seed.1cofounder', role:'Engineer', city:'Ahmedabad', country:'India', bio:'AR/VR developer creating immersive anatomy training simulations for medical students using Meta Quest headsets.', skills:['AR/VR Development','Unity','3D Modeling','Computer Vision'], interests:['Medical Education Innovation','Augmented Reality Surgery','Digital Health'], stage:'Idea', commit:'Part Time', lookingFor:['Clinician','Educator'] },
    { name:'Pranav Joshi', email:'pranav.joshi@seed.1cofounder', role:'Engineer', city:'Jaipur', country:'India', bio:'Backend engineer building ABDM-compliant health information exchange APIs for the Ayushman Bharat Digital Mission.', skills:['Backend Development','API Development','FHIR','Microservices'], interests:['Digital Health','Health Data','EHR Innovation'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Policy Maker'] },
    { name:'Ishaan Roy', email:'ishaan.roy@seed.1cofounder', role:'Engineer', city:'Bangalore', country:'India', bio:'ML engineer building time-series prediction models for ICU patient deterioration using multimodal vital sign data.', skills:['Machine Learning','Time Series Analysis','Deep Learning','Python'], interests:['AI Healthcare','Hospital Automation','Predictive Analytics'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Data Scientist'] },

    // --- 15 BIOMEDICAL ENGINEERS ---
    { name:'Arjun Pillai', email:'arjun.pillai@seed.1cofounder', role:'Engineer', city:'Bangalore', country:'India', bio:'Biomedical engineer designing low-cost pulse oximeter probes for neonatal monitoring in district hospitals.', skills:['Biomedical Engineering','Medical Devices','Embedded Systems','PCB Design'], interests:['Medical Devices','Point-of-Care Testing','Pediatric Health'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Regulatory Specialist'] },
    { name:'Simran Kaur', email:'simran.kaur@seed.1cofounder', role:'Engineer', city:'Chandigarh', country:'India', bio:'Biosensor researcher developing paper-based lateral flow assays for rapid infectious disease screening.', skills:['Biosensors','Microfluidics','Diagnostics','Lab Automation'], interests:['Point-of-Care Testing','Diagnostics','Infectious Disease'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Business Operator'] },
    { name:'Akash Mukherjee', email:'akash.mukherjee@seed.1cofounder', role:'Engineer', city:'Kolkata', country:'India', bio:'Medical device engineer building portable ultrasound probe interfaces for AI-guided point-of-care imaging.', skills:['Biomedical Engineering','Signal Processing','Embedded Systems','Ultrasound'], interests:['Medical Devices','AI Healthcare','Point-of-Care Testing'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','AI Engineer'] },
    { name:'Deepika Jain', email:'deepika.jain@seed.1cofounder', role:'Engineer', city:'Delhi', country:'India', bio:'Prosthetics engineer creating 3D-printed myoelectric hands with sensory feedback for amputees in India.', skills:['Prosthetics','3D Printing','Biomaterials','Rehabilitation'], interests:['Medical Devices','Smart Prosthetics','Rehabilitation'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Business Operator'] },
    { name:'Manoj Hegde', email:'manoj.hegde@seed.1cofounder', role:'Engineer', city:'Bangalore', country:'India', bio:'Wearable technology engineer developing continuous non-invasive blood pressure monitoring wristbands.', skills:['Wearables','Signal Processing','Embedded Systems','Biosensors'], interests:['Wearable Health Tech','Remote Monitoring','Chronic Disease Management'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Data Scientist'] },
    { name:'Anjali Thakur', email:'anjali.thakur@seed.1cofounder', role:'Engineer', city:'Mumbai', country:'India', bio:'Tissue engineering researcher working on bioprinted skin grafts for burn patients using patient-derived cells.', skills:['Tissue Engineering','Biomaterials','Cell Biology','3D Printing'], interests:['Regenerative Medicine','3D Printing','Biomaterials'], stage:'Idea', commit:'Part Time', lookingFor:['Clinician','Researcher'] },
    { name:'Saurabh Pandey', email:'saurabh.pandey@seed.1cofounder', role:'Engineer', city:'Hyderabad', country:'India', bio:'Drug delivery engineer designing nanoparticle-based targeted chemotherapy delivery systems for solid tumors.', skills:['Drug Delivery Systems','Nanotechnology','Pharmacology','Biomaterials'], interests:['Nanomedicine','Drug Delivery','Oncology Innovation'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Researcher'] },
    { name:'Roshni Iyer', email:'roshni.iyer@seed.1cofounder', role:'Engineer', city:'Chennai', country:'India', bio:'Lab automation engineer building robotic sample handling systems for high-throughput diagnostic laboratories.', skills:['Lab Automation','Robotics','Microfluidics','Embedded Systems'], interests:['Hospital Automation','Diagnostics','Medical Devices'], stage:'Exploring', commit:'Part Time', lookingFor:['Clinician','Business Operator'] },
    { name:'Vishal Gupta', email:'vishal.gupta@seed.1cofounder', role:'Engineer', city:'Pune', country:'India', bio:'Implantable device engineer developing biodegradable cardiac stents with drug-eluting polymer coatings.', skills:['Implantable Devices','Biomaterials','Material Science','Biomedical Engineering'], interests:['Medical Devices','Cardio Innovation','Biomaterials'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Regulatory Specialist'] },
    { name:'Neelam Sharma', email:'neelam.sharma@seed.1cofounder', role:'Engineer', city:'Jaipur', country:'India', bio:'Medical imaging engineer developing affordable digital X-ray detector panels for small-town diagnostic centers.', skills:['Medical Imaging','Signal Processing','Embedded Systems','Biomedical Engineering'], interests:['Medical Devices','Diagnostics','Rural Healthcare'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Business Operator'] },
    { name:'Tarun Verma', email:'tarun.verma@seed.1cofounder', role:'Engineer', city:'Ahmedabad', country:'India', bio:'Microfluidics researcher designing lab-on-chip devices for rapid complete blood count analysis at point of care.', skills:['Microfluidics','Biosensors','Lab-on-a-Chip','MEMS'], interests:['Point-of-Care Testing','Diagnostics','Medical Devices'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Business Operator'] },
    { name:'Preeti Choudhary', email:'preeti.choudhary@seed.1cofounder', role:'Engineer', city:'Delhi', country:'India', bio:'Rehabilitation engineer developing EMG-controlled exoskeletons for stroke patient upper limb recovery.', skills:['Rehabilitation','Signal Processing','Biomechanics','Embedded Systems'], interests:['Rehabilitation','Smart Prosthetics','Neurotechnology'], stage:'Idea', commit:'Part Time', lookingFor:['Clinician','Researcher'] },
    { name:'Gaurav Sinha', email:'gaurav.sinha@seed.1cofounder', role:'Engineer', city:'Mumbai', country:'India', bio:'Optical engineer building low-cost portable fluorescence microscopes for malaria parasite detection in blood smears.', skills:['Optical Engineering','Medical Imaging','Biomedical Engineering','Microscopy'], interests:['Diagnostics','Point-of-Care Testing','Rural Healthcare'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Public Health Expert'] },
    { name:'Divya Rajan', email:'divya.rajan@seed.1cofounder', role:'Engineer', city:'Bangalore', country:'India', bio:'Biomedical signal processing engineer creating real-time fetal heart rate monitoring systems from maternal abdominal ECG.', skills:['Signal Processing','Biomedical Engineering','Embedded Systems','Machine Learning'], interests:['Womens Health','Medical Devices','Remote Monitoring'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Data Scientist'] },
    { name:'Ashwin Nair', email:'ashwin.nair@seed.1cofounder', role:'Engineer', city:'Chennai', country:'India', bio:'Medical robotics engineer developing laparoscopic surgery training simulators with haptic feedback for surgical residents.', skills:['Robotic Surgery','Haptics','Embedded Systems','3D Printing'], interests:['Surgical Robotics','Medical Education Innovation','Medical Devices'], stage:'Idea', commit:'Part Time', lookingFor:['Clinician','Software Engineer'] },

    // --- 10 DATA SCIENTISTS ---
    { name:'Arun Khanna', email:'arun.khanna@seed.1cofounder', role:'Data Scientist', city:'Bangalore', country:'India', bio:'Health data scientist building sepsis prediction models validated across 15 ICUs. Published in Lancet Digital Health.', skills:['Data Science','Statistical Modeling','Biostatistics','Python'], interests:['AI Healthcare','Predictive Analytics','Hospital Automation'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Software Engineer'] },
    { name:'Neha Sharma', email:'neha.s@seed.1cofounder', role:'Data Scientist', city:'Delhi', country:'India', bio:'Epidemiologist using geospatial analysis to map disease outbreak patterns and optimize public health resource allocation.', skills:['Epidemiology','Geospatial Analysis','Biostatistics','R'], interests:['Public Health Programs','Disease Surveillance','Health Data'], stage:'Exploring', commit:'Part Time', lookingFor:['Clinician','Software Engineer'] },
    { name:'Rajat Malhotra', email:'rajat.malhotra@seed.1cofounder', role:'Data Scientist', city:'Mumbai', country:'India', bio:'Clinical NLP researcher extracting structured outcomes data from 2M+ unstructured radiology reports for quality metrics.', skills:['Natural Language Processing','Data Science','Health Informatics','Python'], interests:['AI Healthcare','Health Data','Clinical Decision Support'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Product Manager'] },
    { name:'Surbhi Agarwal', email:'surbhi.agarwal@seed.1cofounder', role:'Data Scientist', city:'Hyderabad', country:'India', bio:'Bioinformatician analyzing whole-genome sequencing data for pharmacogenomic drug response prediction in Indian populations.', skills:['Bioinformatics','Genomics','Statistical Modeling','Python'], interests:['Precision Medicine','Pharmacogenomics','Drug Discovery'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Researcher'] },
    { name:'Mohit Bansal', email:'mohit.bansal@seed.1cofounder', role:'Data Scientist', city:'Pune', country:'India', bio:'Health economist using claims data analysis to identify cost-effective treatment pathways for chronic disease management.', skills:['Health Economics','Data Science','Business Intelligence','SQL'], interests:['Value-Based Care','Health Insurance Innovation','Health Data'], stage:'Exploring', commit:'Part Time', lookingFor:['Clinician','Business Operator'] },
    { name:'Ankita Roy', email:'ankita.roy@seed.1cofounder', role:'Data Scientist', city:'Kolkata', country:'India', bio:'Real-world evidence researcher building observational study pipelines from electronic health record data for drug safety monitoring.', skills:['Real-World Evidence','Biostatistics','Data Engineering','SAS'], interests:['Drug Discovery','Clinical Trial Innovation','Health Data'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Regulatory Specialist'] },
    { name:'Kartik Srinivasan', email:'kartik.s@seed.1cofounder', role:'Data Scientist', city:'Chennai', country:'India', bio:'Wearable data scientist building activity recognition models from accelerometer data for Parkinson tremor monitoring.', skills:['Data Science','Machine Learning','Time Series Analysis','Wearable Data'], interests:['Wearable Health Tech','Neurotechnology','AI Healthcare'], stage:'MVP', commit:'Full Time', lookingFor:['Clinician','Hardware Engineer'] },
    { name:'Pooja Nair', email:'pooja.nair@seed.1cofounder', role:'Data Scientist', city:'Bangalore', country:'India', bio:'Survey methodologist designing digital health assessment tools measuring patient-reported outcomes at population scale.', skills:['Survey Design','Biostatistics','Data Visualization','Public Health'], interests:['Population Health','Health Data','Digital Health'], stage:'Exploring', commit:'Part Time', lookingFor:['Clinician','Product Manager'] },
    { name:'Vikas Chandra', email:'vikas.chandra@seed.1cofounder', role:'Data Scientist', city:'Delhi', country:'India', bio:'Computer-aided detection researcher building mammography screening AI models trained on Indian breast density patterns.', skills:['Machine Learning','Medical Image Analysis','Deep Learning','Data Science'], interests:['AI Healthcare','Diagnostics','Womens Health'], stage:'Validation', commit:'Full Time', lookingFor:['Clinician','Software Engineer'] },
    { name:'Ritika Joshi', email:'ritika.joshi@seed.1cofounder', role:'Data Scientist', city:'Ahmedabad', country:'India', bio:'A/B testing specialist running clinical workflow optimization experiments across a 500-bed hospital chain.', skills:['A/B Testing','Statistical Modeling','Business Intelligence','Python'], interests:['Hospital Automation','Healthcare Operations','Health Data'], stage:'Exploring', commit:'Part Time', lookingFor:['Clinician','Product Manager'] },

    // --- 10 PRODUCT MANAGERS / BUSINESS ---
    { name:'Siddharth Kapoor', email:'siddharth.k@seed.1cofounder', role:'Business Operator', city:'Mumbai', country:'India', bio:'Ex-McKinsey healthcare consultant now building a SaaS platform for hospital supply chain optimization.', skills:['Startup Strategy','Healthcare Operations','Fundraising','Strategic Planning'], interests:['Health Tech Startups','Hospital Automation','Supply Chain Healthcare'], stage:'MVP', commit:'Full Time', lookingFor:['Software Engineer','Clinician'] },
    { name:'Aditi Mehta', email:'aditi.mehta@seed.1cofounder', role:'Product Manager', city:'Bangalore', country:'India', bio:'Product manager with 6 years in digital health. Led launch of India largest teleconsultation feature serving 2M patients.', skills:['Product Management','UX Research','Growth Marketing','Healthcare UX'], interests:['Digital Health','Telemedicine','Health Apps'], stage:'Exploring', commit:'Full Time', lookingFor:['Software Engineer','Clinician'] },
    { name:'Gaurav Sethi', email:'gaurav.sethi@seed.1cofounder', role:'Business Operator', city:'Delhi', country:'India', bio:'Serial healthtech entrepreneur. Previous exit in pharmacy logistics. Now exploring AI-powered clinical trial recruitment.', skills:['Startup Strategy','Fundraising','Sales','Partnership Development'], interests:['Health Tech Startups','Clinical Trial Innovation','Drug Discovery'], stage:'Idea', commit:'Full Time', lookingFor:['AI Engineer','Clinical Researcher'] },
    { name:'Prerna Ahuja', email:'prerna.ahuja@seed.1cofounder', role:'Product Manager', city:'Hyderabad', country:'India', bio:'Product lead at a diagnostics company. Designed the specimen tracking system used by 400+ labs across South India.', skills:['Product Management','Healthcare Operations','UX Design','Market Research'], interests:['Diagnostics','Hospital Automation','Digital Health'], stage:'Exploring', commit:'Part Time', lookingFor:['Software Engineer','Clinician'] },
    { name:'Naveen Rao', email:'naveen.rao@seed.1cofounder', role:'Business Operator', city:'Chennai', country:'India', bio:'MBA from ISB with 8 years in hospital administration. Building a chain of AI-first diagnostic clinics in tier-2 cities.', skills:['Healthcare Operations','Hospital Administration','Fundraising','Strategic Planning'], interests:['Health Tech Startups','Diagnostics','Rural Healthcare'], stage:'Validation', commit:'Full Time', lookingFor:['AI Engineer','Software Engineer'] },
    { name:'Meghna Bose', email:'meghna.bose@seed.1cofounder', role:'Product Manager', city:'Kolkata', country:'India', bio:'Healthcare product designer specializing in patient-facing interfaces. Reduced appointment no-shows by 34% through UX improvements.', skills:['Product Management','UX Design','Healthcare UX','Patient Journey Mapping'], interests:['Digital Health','Health Apps','Care Coordination'], stage:'Exploring', commit:'Full Time', lookingFor:['Software Engineer','Clinician'] },
    { name:'Vinay Agrawal', email:'vinay.agrawal@seed.1cofounder', role:'Business Operator', city:'Pune', country:'India', bio:'Health insurance domain expert building value-based care analytics tools for TPAs and insurance companies.', skills:['Healthcare Finance','Insurance Analytics','Business Development','Data Analysis'], interests:['Health Insurance Innovation','Value-Based Care','Health Data'], stage:'Validation', commit:'Full Time', lookingFor:['Software Engineer','Data Scientist'] },
    { name:'Swati Mishra', email:'swati.mishra@seed.1cofounder', role:'Product Manager', city:'Bangalore', country:'India', bio:'Growth PM who scaled a mental health app from 10K to 500K users. Expertise in behavioral health product design.', skills:['Product Management','Growth Marketing','A/B Testing','User Testing'], interests:['Mental Health','Digital Therapeutics','Health Apps'], stage:'MVP', commit:'Full Time', lookingFor:['Software Engineer','Clinician'] },
    { name:'Kunal Bhargava', email:'kunal.bhargava@seed.1cofounder', role:'Business Operator', city:'Ahmedabad', country:'India', bio:'Regulatory affairs specialist with pharma background. Helping med-device startups navigate CDSCO and BIS approvals.', skills:['Regulatory Affairs','FDA Compliance','Market Access','Quality Improvement'], interests:['Medical Devices','Medtech Commercialization','Regulatory Affairs'], stage:'Exploring', commit:'Part Time', lookingFor:['Biomedical Engineer','Clinician'] },
    { name:'Radhika Goyal', email:'radhika.goyal@seed.1cofounder', role:'Business Operator', city:'Jaipur', country:'India', bio:'Impact investor evaluating health-tech startups in Rajasthan. Mentoring 5 early-stage founders on go-to-market strategy.', skills:['Impact Investing','Fundraising','Startup Strategy','Market Research'], interests:['Health Tech Startups','Impact Investing in Health','Rural Healthcare'], stage:'Exploring', commit:'Part Time', lookingFor:['Software Engineer','Clinician'] },

    // --- 10 RESEARCHERS ---
    { name:'Dr Sanjay Mukherjee', email:'sanjay.m@seed.1cofounder', role:'Researcher', city:'Kolkata', country:'India', bio:'Computational biology researcher developing protein structure prediction tools for tropical disease drug targets.', skills:['Molecular Biology','Drug Discovery','Bioinformatics','Proteomics'], interests:['Drug Discovery','Precision Medicine','AI Healthcare'], stage:'Idea', commit:'Part Time', lookingFor:['AI Engineer','Software Engineer'] },
    { name:'Dr Anisha Pillai', email:'anisha.pillai@seed.1cofounder', role:'Researcher', city:'Bangalore', country:'India', bio:'Immunology researcher studying T-cell responses in Indian COVID convalescent patients for next-gen vaccine design.', skills:['Immunology Research','Clinical Research','Genomics','Biostatistics'], interests:['Vaccine Development','Immunotherapy','Precision Medicine'], stage:'Idea', commit:'Part Time', lookingFor:['Data Scientist','Software Engineer'] },
    { name:'Dr Pradeep Sharma', email:'pradeep.sharma@seed.1cofounder', role:'Researcher', city:'Delhi', country:'India', bio:'Health systems researcher evaluating mHealth intervention effectiveness in improving maternal care outcomes in UP.', skills:['Health Economics','Clinical Trials','Public Health Programs','Systematic Reviews'], interests:['Global Health','Womens Health','Rural Healthcare'], stage:'Validation', commit:'Part Time', lookingFor:['Software Engineer','Public Health Expert'] },
    { name:'Dr Radhika Menon', email:'radhika.menon@seed.1cofounder', role:'Researcher', city:'Chennai', country:'India', bio:'Neuroscience researcher mapping cortical biomarkers of treatment-resistant depression using functional MRI analysis.', skills:['Neuroscience','Medical Imaging','Statistical Modeling','fMRI'], interests:['Mental Health','Neurotechnology','Brain-Computer Interfaces'], stage:'Idea', commit:'Part Time', lookingFor:['AI Engineer','Data Scientist'] },
    { name:'Dr Vaibhav Gupta', email:'vaibhav.gupta@seed.1cofounder', role:'Researcher', city:'Mumbai', country:'India', bio:'Microbiome researcher characterizing gut flora patterns in Indian IBD patients for personalized probiotic therapy.', skills:['Microbiome','Genomics','Bioinformatics','Clinical Research'], interests:['Microbiome','Precision Medicine','Nutrition Tech'], stage:'Idea', commit:'Part Time', lookingFor:['Data Scientist','Business Operator'] },
    { name:'Dr Nandini Rao', email:'nandini.rao@seed.1cofounder', role:'Researcher', city:'Hyderabad', country:'India', bio:'Pharmacogenomics researcher identifying genetic variants affecting warfarin dosing in South Indian populations.', skills:['Pharmacogenomics','Genomics','Clinical Trials','Biostatistics'], interests:['Precision Medicine','Pharmacogenomics','Drug Discovery'], stage:'Validation', commit:'Part Time', lookingFor:['Software Engineer','Clinician'] },
    { name:'Dr Amit Saxena', email:'amit.saxena@seed.1cofounder', role:'Researcher', city:'Pune', country:'India', bio:'Stem cell researcher developing iPSC-derived cardiomyocyte models for high-throughput cardiac drug toxicity screening.', skills:['Stem Cell Research','Cell Biology','Drug Discovery','Tissue Engineering'], interests:['Regenerative Medicine','Drug Discovery','Cardio Innovation'], stage:'Idea', commit:'Part Time', lookingFor:['Biomedical Engineer','Business Operator'] },
    { name:'Dr Sunita Chandra', email:'sunita.chandra@seed.1cofounder', role:'Researcher', city:'Delhi', country:'India', bio:'Clinical trial methodologist designing adaptive trial protocols for rare pediatric diseases with small sample sizes.', skills:['Clinical Trials','Biostatistics','Outcomes Research','Grant Writing'], interests:['Clinical Trial Innovation','Pediatric Health','Drug Discovery'], stage:'Exploring', commit:'Part Time', lookingFor:['Data Scientist','Regulatory Specialist'] },
    { name:'Dr Ashok Iyer', email:'ashok.iyer@seed.1cofounder', role:'Researcher', city:'Bangalore', country:'India', bio:'Cancer genomics researcher identifying actionable mutations in head-and-neck cancers prevalent in South Asian populations.', skills:['Genomics','Oncology','Bioinformatics','Clinical Research'], interests:['Oncology Innovation','Precision Medicine','Genomics'], stage:'Validation', commit:'Part Time', lookingFor:['AI Engineer','Software Engineer'] },
    { name:'Dr Kavya Patel', email:'kavya.patel@seed.1cofounder', role:'Researcher', city:'Ahmedabad', country:'India', bio:'Environmental health researcher correlating air quality sensor data with respiratory hospital admissions across Gujarat.', skills:['Environmental Health','Epidemiology','Data Analysis','Public Health'], interests:['Climate & Health','Preventive Medicine','Health Data'], stage:'Idea', commit:'Part Time', lookingFor:['Data Scientist','Software Engineer'] },
  ];

  // Admin user
  const adminUser = {
    id: uuidv4(), name: 'Platform Admin', email: 'admin@1cofounder.ai', password_hash: await bcrypt.hash('Admin@1cf2026', 10),
    role: 'Administrator', city: '', country: '', location: '', bio: 'Platform administrator', profile_photo: '',
    skills: [], interests: [], startup_stage: '', commitment_level: '', looking_for: [],
    verified_status: true, profile_complete: false, is_admin: true, is_suspended: false, report_count: 0,
    email_verified: true, notification_preferences: { matches: true, messages: true, problems: true, projects: true },
    created_at: new Date().toISOString()
  };

  const userDocs = users.map((u, i) => ({
    id: uuidv4(), name: u.name, email: u.email, password_hash: defaultPwHash,
    role: u.role, city: u.city, country: u.country, location: `${u.city}, ${u.country}`,
    bio: u.bio, profile_photo: '', skills: u.skills, interests: u.interests,
    startup_stage: u.stage, commitment_level: u.commit, looking_for: u.lookingFor,
    verified_status: (i % 3 === 0), profile_complete: true, is_admin: false, is_suspended: false,
    report_count: 0, email_verified: true,
    notification_preferences: { matches: true, messages: true, problems: true, projects: true },
    created_at: new Date(Date.now() - Math.random() * 30 * 86400000).toISOString()
  }));

  userDocs.push(adminUser);

  // Clear and insert
  await db.collection('users').deleteMany({ email: { $regex: /@seed\.1cofounder$|^admin@1cofounder\.ai$/ } });
  await db.collection('users').insertMany(userDocs);
  console.log(`Inserted ${userDocs.length} users`);

  // ===== PROBLEMS =====
  const doctorUsers = userDocs.filter(u => u.role === 'Doctor');
  const researcherUsers = userDocs.filter(u => u.role === 'Researcher');
  const problemCreators = [...doctorUsers.slice(0, 15), ...researcherUsers.slice(0, 5)];

  const problemsData = [
    { title:'AI-powered ECG triage system for rural primary health centers', desc:'Build a deep learning model that analyzes single-lead ECG signals from low-cost devices and flags life-threatening arrhythmias within 30 seconds. Target deployment in PHCs where no cardiologist is available.', skills:['AI Engineer','Cardiologist','Biomedical Engineer'], ctx:'Primary health centers in rural India see 200+ patients daily but lack specialists to interpret ECGs. Delayed diagnosis of STEMI and critical arrhythmias leads to preventable deaths during referral.' },
    { title:'ICU alarm fatigue reduction through intelligent alert prioritization', desc:'Develop a context-aware alarm management system that reduces false positive ICU monitor alarms by 80% using multi-parameter correlation and patient acuity scoring.', skills:['AI Engineer','Data Scientist','Clinician'], ctx:'ICU nurses face 150-400 alarms per patient per day. 85-99% are false positives leading to alarm fatigue. Critical alarms get missed among the noise causing adverse events.' },
    { title:'AI-assisted radiology triage for emergency CT head scans', desc:'Create an AI system that automatically triages non-contrast CT head scans for intracranial hemorrhage and alerts radiologists to critical findings within 2 minutes of acquisition.', skills:['AI Engineer','Software Engineer','Clinician'], ctx:'Stroke and trauma patients in emergency departments wait 30-60 minutes for radiology reads. Every minute of delay in hemorrhage detection increases mortality and disability.' },
    { title:'Wearable maternal health monitor for high-risk pregnancies', desc:'Design a comfortable wearable device that continuously monitors fetal heart rate, uterine contractions, and maternal vitals, sending real-time alerts to ANM workers and obstetricians.', skills:['Biomedical Engineer','Hardware Engineer','Clinician'], ctx:'India has 44,000 maternal deaths annually. Most occur in the last trimester due to undetected preeclampsia, fetal distress, or preterm labor in areas with no monitoring infrastructure.' },
    { title:'Automated medication reconciliation system for hospital transfers', desc:'Build an NLP-based system that automatically reconciles medication lists across hospital departments, flagging drug interactions and duplicate prescriptions during patient transfers.', skills:['Software Engineer','Data Scientist','Clinician'], ctx:'Medication errors during hospital transfers affect 60% of patients. Manual reconciliation is slow and error-prone. Adverse drug events from reconciliation failures cost $1.3B annually in India.' },
    { title:'Digital mental health screening tool for college students', desc:'Create a culturally adapted digital screening platform that detects depression, anxiety, and suicidal ideation among Indian college students using validated psychometric instruments and behavioral signals.', skills:['Software Engineer','UX Researcher','Clinician'], ctx:'1 in 5 Indian college students shows signs of depression. Stigma prevents 85% from seeking help. Most campuses have only 1 counselor for 5000+ students.' },
    { title:'Sepsis prediction model using routinely collected hospital data', desc:'Develop and validate a machine learning model that predicts sepsis onset 6-12 hours before clinical recognition using only data available in basic hospital EMR systems.', skills:['AI Engineer','Data Scientist','Clinician'], ctx:'Sepsis kills 11 million people globally each year. Early detection improves survival by 30% but clinical recognition is often delayed. Most Indian hospitals lack the lab infrastructure for complex biomarker panels.' },
    { title:'Clinical decision support for rational antibiotic prescribing', desc:'Build a real-time clinical decision support system that recommends evidence-based antibiotic regimens based on local resistance patterns, patient history, and culture sensitivity data.', skills:['Software Engineer','Data Scientist','Clinician'], ctx:'India has among the highest antibiotic resistance rates globally. 70% of prescriptions in outpatient settings are inappropriate. No system currently integrates local antibiogram data into prescribing workflows.' },
    { title:'Telemedicine platform optimized for low-bandwidth rural connectivity', desc:'Design a telemedicine system that delivers quality video consultations over 2G/3G networks with adaptive bitrate streaming, offline appointment booking, and asynchronous store-and-forward capabilities.', skills:['Software Engineer','Product Manager','Clinician'], ctx:'600 million Indians lack access to specialist healthcare. Existing telemedicine platforms require 4G connectivity, excluding 65% of rural areas. Store-and-forward options are limited.' },
    { title:'AI-powered diabetic foot ulcer monitoring system', desc:'Develop a smartphone camera-based system that tracks wound healing progress, detects early infection signs, and generates standardized wound assessment reports for remote diabetic foot care.', skills:['AI Engineer','Mobile Developer','Clinician'], ctx:'India has 77 million diabetics. 25% develop foot ulcers. 85% of amputations are preceded by ulcers that were treatable if caught early. Rural patients travel 100km+ for wound specialist visits.' },
    { title:'Hospital workflow optimization for outpatient department bottlenecks', desc:'Create a simulation and optimization engine that dynamically adjusts appointment scheduling, resource allocation, and patient flow to reduce OPD wait times by 50%.', skills:['Data Scientist','Software Engineer','Healthcare Consultant'], ctx:'Average OPD wait time in Indian public hospitals is 2-4 hours. Patients often leave without being seen. Inefficient scheduling wastes 30% of physician capacity.' },
    { title:'Voice-enabled health record system for low-literacy populations', desc:'Build a multilingual voice interface that allows community health workers to record patient encounters in Hindi, Tamil, or Bengali through natural speech, auto-generating structured health records.', skills:['AI Engineer','Software Engineer','UX Researcher'], ctx:'40% of Indian community health workers have limited digital literacy. Paper records are lost or illegible. Voice-based systems can capture 3x more clinical data in the same time.' },
    { title:'Interoperable health data exchange for India ABDM ecosystem', desc:'Design and implement FHIR-compliant APIs that enable seamless health record exchange between private hospital EMRs and the Ayushman Bharat Digital Mission health locker infrastructure.', skills:['Software Engineer','Data Scientist','Healthcare Consultant'], ctx:'India 200,000+ hospitals use 50+ different EMR systems. Patient data is fragmented across providers. ABDM aims to create unified health records but adoption requires technical bridges.' },
    { title:'Low-cost wearable for continuous neonatal jaundice monitoring', desc:'Engineer a non-invasive transcutaneous bilirubinometer wearable that continuously monitors neonatal jaundice levels and alerts nursing staff when phototherapy thresholds are reached.', skills:['Biomedical Engineer','Hardware Engineer','Clinician'], ctx:'Neonatal jaundice affects 60% of newborns. Severe cases cause kernicterus and permanent brain damage. Current monitoring requires repeated heel-prick blood draws, causing pain and infection risk.' },
    { title:'AI model for tuberculosis detection from chest X-rays', desc:'Build a high-sensitivity deep learning model for automated TB screening from digital chest X-rays, optimized for deployment on edge devices in TB screening camps.', skills:['AI Engineer','Data Scientist','Clinician'], ctx:'India accounts for 27% of global TB cases. Chest X-ray screening camps generate thousands of images but lack radiologists. Automated screening could increase case detection by 40%.' },
    { title:'Patient deterioration early warning system for general wards', desc:'Develop a real-time early warning score system that continuously monitors general ward patients and alerts nursing teams to deterioration events before they require ICU transfer.', skills:['AI Engineer','Software Engineer','Clinician'], ctx:'Unexpected cardiac arrests in general wards have 85% mortality. 80% of these patients show deterioration signs 6-8 hours before arrest that are missed by intermittent manual vital checks.' },
    { title:'Portable spirometry device with AI-powered interpretation', desc:'Design an affordable handheld spirometer with built-in AI that performs quality-controlled pulmonary function tests and generates diagnostic reports without needing a trained technician.', skills:['Biomedical Engineer','AI Engineer','Clinician'], ctx:'300 million Indians have chronic respiratory diseases. Spirometry testing is only available in 5% of primary care facilities. Most existing devices require trained technicians to ensure test quality.' },
    { title:'Blood bank inventory optimization using demand forecasting', desc:'Create a machine learning system that predicts blood component demand at hospital blood banks 72 hours ahead, reducing wastage of platelets and rare blood types.', skills:['Data Scientist','Software Engineer','Healthcare Consultant'], ctx:'Indian blood banks waste 6% of collected units due to expiry. Platelet shelf life is only 5 days. Rare blood type shortages cause surgical cancellations. No predictive system exists.' },
    { title:'Digital pathology AI for cervical cancer screening at scale', desc:'Develop a whole-slide image analysis pipeline that automates Pap smear screening for cervical pre-cancer, enabling high-throughput processing at population screening centers.', skills:['AI Engineer','Data Scientist','Clinician'], ctx:'Cervical cancer kills 75,000 Indian women annually. Cytology-based screening requires trained pathologists who are scarce. AI could enable screening at 10x throughput with consistent quality.' },
    { title:'Smart ambulance dispatch and routing optimization', desc:'Build a real-time ambulance dispatch system that optimizes vehicle assignment and routing based on emergency severity, traffic conditions, hospital capacity, and specialist availability.', skills:['Software Engineer','Data Scientist','Product Manager'], ctx:'Average ambulance response time in Indian cities is 20-30 minutes. 30% of trauma deaths are preventable with faster transport. Current dispatch is manual and doesn not account for real-time hospital capacity.' },
  ];

  const problemDocs = problemsData.map((p, i) => ({
    id: uuidv4(), title: p.title, description: p.desc, clinical_context: p.ctx,
    skills_required: p.skills, creator_id: problemCreators[i].id, report_count: 0,
    created_at: new Date(Date.now() - Math.random() * 20 * 86400000).toISOString()
  }));

  await db.collection('problems').deleteMany({ creator_id: { $in: userDocs.map(u => u.id) } });
  await db.collection('problems').insertMany(problemDocs);
  console.log(`Inserted ${problemDocs.length} problems`);

  // ===== PROJECTS =====
  const projectCreators = [
    ...userDocs.filter(u => u.role === 'Business Operator').slice(0, 4),
    ...doctorUsers.slice(0, 2),
    ...userDocs.filter(u => u.role === 'Engineer').slice(0, 2),
  ];

  const projectsData = [
    { name:'ECG AI Assist', desc:'AI-powered ECG interpretation tool designed for primary healthcare clinics in rural India. Analyzes single-lead ECG in real-time, flags critical arrhythmias, and generates cardiologist-readable reports. Targeting deployment across 5000 PHCs in phase one.', stage:'Validation' },
    { name:'ICU Smart Monitor', desc:'Intelligent ICU alarm management platform that correlates multi-parameter vital signs with patient context to reduce false alarms by 80%. Integrates with existing Philips and GE patient monitors through HL7 interfaces.', stage:'MVP' },
    { name:'Maternal Health Wearable', desc:'Continuous fetal and maternal monitoring wearable for high-risk pregnancies. Belt-form device tracks fetal heart rate, uterine activity, and maternal SpO2. Sends real-time alerts to care providers via mobile app.', stage:'Validation' },
    { name:'AI Radiology Triage', desc:'Emergency radiology AI that auto-triages CT head scans for hemorrhage, midline shift, and mass effect. Reduces critical finding notification time from 45 minutes to under 3 minutes. Trained on 500K Indian hospital scans.', stage:'MVP' },
    { name:'Hospital Workflow OS', desc:'Operating system for hospital outpatient departments. Uses simulation modeling to optimize scheduling, reduce wait times, and dynamically allocate resources based on real-time patient flow data.', stage:'Idea' },
    { name:'MindBridge', desc:'Culturally adapted digital mental health screening and therapy platform for Indian youth. Combines validated screening tools with AI-guided CBT modules in Hindi and English. Partnered with 12 university campuses.', stage:'Validation' },
    { name:'Remote Patient Monitor', desc:'End-to-end remote patient monitoring platform for chronic disease management. Integrates data from glucometers, BP monitors, and pulse oximeters. AI-powered clinical dashboards alert care teams to deterioration trends.', stage:'MVP' },
    { name:'Clinical Data Exchange', desc:'FHIR-compliant health information exchange platform enabling seamless medical record sharing across hospital EMR systems. Built for Ayushman Bharat Digital Mission compatibility. Currently integrating with 3 major EMR vendors.', stage:'Idea' },
  ];

  const projectDocs = projectsData.map((p, i) => ({
    id: uuidv4(), name: p.name, description: p.desc, stage: p.stage,
    creator_id: projectCreators[i].id,
    created_at: new Date(Date.now() - Math.random() * 15 * 86400000).toISOString()
  }));

  // Also add project members (creator as member)
  const memberDocs = projectDocs.map(p => ({
    id: uuidv4(), project_id: p.id, user_id: p.creator_id, role: 'Creator',
    joined_at: p.created_at
  }));

  await db.collection('projects').deleteMany({ creator_id: { $in: userDocs.map(u => u.id) } });
  await db.collection('project_members').deleteMany({ user_id: { $in: userDocs.map(u => u.id) } });
  await db.collection('projects').insertMany(projectDocs);
  await db.collection('project_members').insertMany(memberDocs);
  console.log(`Inserted ${projectDocs.length} projects with members`);

  console.log('\n=== SEED COMPLETE ===');
  console.log(`Users: ${userDocs.length} (100 profiles + 1 admin)`);
  console.log(`Problems: ${problemDocs.length}`);
  console.log(`Projects: ${projectDocs.length}`);
  console.log('Admin login: admin@1cofounder.ai / Admin@1cf2026');
  console.log('Default user password: Welcome@1cf');

  await client.close();
}

seed().catch(e => { console.error(e); process.exit(1); });
